### ISSUE TITLE
Les nouveaux utilisateurs n'ont pas d'habilitation définis

### ISSUE THREAD

**Issue by Guillaume-Fortin** [Thetyne/BodyReport#1]
Les nouveaux utilisateurs n'ont pas d'habilitation défini par défaut.
Il ne peuvent aller sur aucune page tant qu'un admin ne leur définissent pas une habilitation utilisateur.

**Comment by Thetyne** [comment]
Voir interdire le login aux nouveaux membres tant qu'ils n'ont pas valider leur email.
Pour cela il faudrait gérer une validation de l'email. 

futur développement
