### ISSUE TITLE
Ajout des exercices autres que musculation

### ISSUE THREAD

**Issue by Guillaume-Fortin** [Thetyne/BodyReport#22]
Exercises demandés par les utilisateurs: 
tapis de courses, courses à pied, vélo, vélo elliptique, vélo spinning.

Développer un système de type d'exercises afin de définir les mesures à inscrire dans le carnet d'entrainement 
Exemple durée, intensité, calories brulés, fréquence cardiaque moyenne.

**Comment by JeromeDespret** [comment]
Et corde à sauter !

**Comment by Guillaume-Fortin** [comment]
natation

**Comment by Kentukiii** [comment]
Sport de chambre ;)
